#include <stdio.h>

long long sum_fibonacci(int n){

	int last_two[2];
	int i;

	last_two[0] = 1;
	last_two[1] = 2;

	long long sum = 3;

	while(1){

		last_two[1] = last_two[0] + last_two[1];
		last_two[0] = last_two[1] - last_two[0];

		if ( last_two[1] > n )
			break;
		if ( last_two[1] & 1 )
			sum += last_two[1];
	}

	return sum - 1;

}

int main(){

	/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
	*/

	printf("%lld\n", sum_fibonacci(4000000) );

	return 0;
}